name: firebase_auth_oauth
description: A Flutter plugin that makes it easy to perform OAuth sign in flows using FirebaseAuth. It also includes support for Sign in by Apple for Firebase.
version: 1.0.3
homepage: https://github.com/amrfarid140/firebase_auth_oauth/tree/master/firebase_auth_oauth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_core: ^1.3.0
  firebase: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.amryousef.apple.auth.firebase_auth_oauth
        pluginClass: FirebaseAuthOAuthPlugin
      ios:
        pluginClass: FirebaseAuthOAuthPlugin
      web:
        default_package: firebase_apple_auth_web
